version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            pip install flake8
            flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --output-file test-reports
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
