# Generated by Django 3.0.3 on 2020-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZNOSubject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(null=False, blank=False, max_length=50)),
                (
                    "description",
                    models.TextField(null=True, blank=True, max_length=1000),
                ),
                (
                    "telegram_bot_name",
                    models.CharField(null=True, blank=True, max_length=50),
                ),
                (
                    "viber_bot_name",
                    models.CharField(null=True, blank=True, max_length=50),
                ),
                (
                    "messenger_bot_name",
                    models.CharField(null=True, blank=True, max_length=50),
                ),
                (
                    "whatsapp_bot_name",
                    models.CharField(null=True, blank=True, max_length=50),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
