# Generated by Django 3.0.3 on 2020-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200207_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="znosubject",
            name="messenger_bot_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="telegram_bot_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="viber_bot_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="whatsapp_bot_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
