# Generated by Django 3.0.3 on 2020-02-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200207_2101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="znosubject",
            name="messenger_bot_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="telegram_bot_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="viber_bot_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="whatsapp_bot_name",
            field=models.CharField(max_length=50),
        ),
    ]
