# Generated by Django 3.0.3 on 2020-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200207_2217"),
    ]

    operations = [
        migrations.AddField(
            model_name="znosubject",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
