# Generated by Django 3.0.3 on 2020-02-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200220_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="znosubject",
            name="image_top",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
