# Generated by Django 3.0.3 on 2020-02-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_znosubject_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="znosubject",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/img/"),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="messenger_bot_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="telegram_bot_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="viber_bot_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="whatsapp_bot_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
