# Generated by Django 3.0.3 on 2020-02-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20200211_0147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="znosubject", options={"ordering": ["title_order"]},
        ),
        migrations.AddField(
            model_name="znosubject",
            name="title_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
