# Generated by Django 3.0.3 on 2020-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_znosubject_image_top"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="znosubject",
            options={
                "ordering": ["order"],
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предмети",
            },
        ),
        migrations.AddField(
            model_name="znosubject",
            name="wide_thumbnail",
            field=models.BooleanField(default=False, verbose_name="Широка мініатюра"),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Гасло"
            ),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="image_title",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Зображення мініатюри",
            ),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="image_top",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Основне зображення"
            ),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="messenger_bot_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Messenger бот"
            ),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="telegram_bot_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram бот"
            ),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Назва предмету"),
        ),
        migrations.AlterField(
            model_name="znosubject",
            name="viber_bot_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Viber бот"
            ),
        ),
    ]
