org: vasylstanislavchuk
app: serverless-telegram-bot-app
service: serverless-telegram-bot

provider:
  name: aws
  runtime: python3.7
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    API_ROOT: ${file(./serverless.env.yml):API_ROOT, ''}
    SENTRY_DSN: ${file(./serverless.env.yml):SENTRY_DSN, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements
