org: vasylstanislavchuk
app: serverless-telegram-bot-app
service: serverless-telegram-bot

provider:
  name: aws
  runtime: python3.7
  environment:
    STAGE: ${${self:custom.config}:STAGE}
    TELEGRAM_TOKEN: ${${self:custom.config}:TELEGRAM_TOKEN}
    API_ROOT: ${${self:custom.config}:API_ROOT}
    SENTRY_DSN: ${${self:custom.config}:SENTRY_DSN}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /{subject}

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements

custom:
  stage: ${opt:stage, 'dev'}
  config: file(./config/${self:custom.stage}.json)
