version: '3'

services:
  zno_api:
    image: zno_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
